// ============================================================
// Seed adventure sports for Jammu, Kashmir & Ladakh
// Run: bun run /home/z/my-project/scripts/seed-adventures.ts
// ============================================================
import { db } from '../src/lib/db'

const adventures = [
  // ===== Winter sports (Gulmarg) =====
  {
    id: 'gulmarg-downhill-ski',
    name: 'Downhill Skiing',
    category: 'Skiing',
    destinationId: 'gulmarg',
    season: 'Dec — Apr',
    description: 'Gondola-served resort skiing on the second-highest cable car in the world, dropping 1,700 vertical metres from Apharwat Peak (4,390 m).',
    longDescription: 'Gulmarg is India\'s premier ski resort — the gondola climbs to 4,390 m, with marked runs for beginners on the lower slopes and legendary off-piste terrain above. Eliya partners with certified instructors from the Indian Institute of Skiing and Mountaineering (IISM) for every guest, from first-timers to expert. The snow is famously dry (continental climate), and the season runs December to April with peak powder in January–February.',
    image: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 12500,
    duration: 'Full day',
    difficulty: 'Beginner to Advanced',
    minAge: 8,
    maxGroup: 6,
    gear: '["Skis","Boots","Poles","Helmet","Goggles","Gloves","Avalanche transceiver (off-piste)"]',
    safety: '["Certified IISM guide","Avalanche transceiver training","Gondola rescue cover","First-aid kit"]',
  },
  {
    id: 'gulmarg-heliski',
    name: 'Heli-Skiing',
    category: 'Skiing',
    destinationId: 'gulmarg',
    season: 'Jan — Mar',
    description: 'Helicopter drops onto untracked powder faces in the Pir Panjal range — 3-5 runs per day, 1,500-2,000 m vertical each.',
    longDescription: 'Eliya\'s flagship winter product. Our helicopter (a B3 Squirrel) operates from Gulmarg and drops small groups (4 skiers + 1 guide) onto untracked faces in the Pir Panjal range. Each run delivers 1,500–2,000 vertical metres of dry powder. Guests must be strong intermediate skiers comfortable in variable snow. 3-5 runs per day, weather permitting.',
    image: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 65000,
    duration: 'Full day',
    difficulty: 'Advanced',
    minAge: 18,
    maxGroup: 4,
    gear: '["Fat skis (110mm+ waist)","Avalanche transceiver","Shovel","Probe","Airbag backpack","Helmet"]',
    safety: '["IFMGA-certified guide","Avalanche transceiver check","Helicopter rescue","Satellite phone","First-aid"]',
  },
  {
    id: 'gulmarg-snowboard',
    name: 'Snowboarding',
    category: 'Skiing',
    destinationId: 'gulmarg',
    season: 'Dec — Apr',
    description: 'Same gondola-served terrain as skiing, with a separate snowboard instructor team. Ideal for beginners on the lower bowls.',
    longDescription: 'Gulmarg\'s wide-open bowls and tree runs are perfect for snowboarding. Eliya has a dedicated team of snowboard instructors (not skiers teaching boarding). Beginner lessons happen on the gentle slopes at Kangdori mid-station (3,050 m); advanced riders take the gondola to Apharwat for the big lines.',
    image: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 11000,
    duration: 'Full day',
    difficulty: 'Beginner to Advanced',
    minAge: 10,
    maxGroup: 6,
    gear: '["Snowboard","Boots","Helmet","Wrist guards","Goggles","Gloves"]',
    safety: '["Snowboard-specific instructor","Gondola rescue cover","First-aid kit"]',
  },
  {
    id: 'gulmarg-skintouring',
    name: 'Ski Touring / Skinning',
    category: 'Skiing',
    destinationId: 'gulmarg',
    season: 'Mar — May',
    description: 'Earn your turns — skin up Apharwat Ridge and Mt Apharwat (4,390 m) for descents of 1,000+ vertical metres of spring corn snow.',
    longDescription: 'For experienced skiers who want to escape the lift lines. Eliya\'s UIAGM guides lead day tours from Gulmarg up the Apharwat Ridge — skinning 600-1,000 m up before dropping back to the gondola. Multi-day touring trips reach the Khilanmarg bowl and Alpather Lake. Best in spring (March-May) when the snowpack stabilises and corn snow forms.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 18000,
    duration: 'Full day',
    difficulty: 'Intermediate to Advanced',
    minAge: 16,
    maxGroup: 4,
    gear: '["Touring skis","Skins","Crampons","Ice axe (optional)","Avalanche transceiver","Shovel","Probe"]',
    safety: '["UIAGM guide","Avalanche transceiver","Route assessment","Satellite phone"]',
  },

  // ===== Trekking =====
  {
    id: 'tarsar-marsar-trek',
    name: 'Tarsar–Marsar Twin-Lakes Trek',
    category: 'Trekking',
    destinationId: 'aru',
    season: 'Jul — Sep',
    description: '4-day alpine trek to three high-altitude lakes (Tarsar, Marsar, Sundersar) above 4,000 m in the Great Himalayan Range.',
    longDescription: 'Kashmir\'s most beautiful trek — 4 days from Aru, crossing 4,000 m passes between three turquoise alpine lakes. Tarsar (3,950 m), Marsar (3,900 m) and Sundersar (4,000 m) sit in adjacent valleys separated by sharp ridges. Camp under the Milky Way beside the lakes. Eliya provides pack ponies for gear, a cook, and a UIAGM-certified guide.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 28500,
    duration: '4 days',
    difficulty: 'Intermediate',
    minAge: 14,
    maxGroup: 8,
    gear: '["Trekking boots","Daypack","Sleeping bag (-5°C)","Trekking poles","Rain shell","Warm layers","Headlamp"]',
    safety: '["UIAGM guide","Pack ponies for gear","Cook + meals","First-aid + altitude meds","Satellite phone"]',
  },
  {
    id: 'gangabal-trek',
    name: 'Vishansar–Krishansar–Gangabal Trek',
    category: 'Trekking',
    destinationId: 'sonamarg',
    season: 'Jul — Sep',
    description: '3-day trek out of Sonmarg crossing Nichinai and Gadsar passes (4,200 m) to the sacred Gangabal Lake at the foot of Mt Haramukh.',
    longDescription: 'The classic Kashmir alpine-lakes trek. Starting from Sonmarg, the route climbs through Nichinai Pass (4,100 m) to Vishansar and Krishansar lakes, then over Gadsar Pass (4,200 m) — the highest point — to the sacred Gangabal Lake at 3,570 m, beneath the 5,142 m Mt Haramukh. Three days of trekking, two nights of camping.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 24500,
    duration: '3 days',
    difficulty: 'Intermediate',
    minAge: 14,
    maxGroup: 8,
    gear: '["Trekking boots","Sleeping bag","Trekking poles","Rain shell","Warm layers","Headlamp"]',
    safety: '["UIAGM guide","Pack ponies","Cook + meals","First-aid","Satellite phone"]',
  },
  {
    id: 'kolahoi-glacier-trek',
    name: 'Kolahoi Glacier Expedition',
    category: 'Trekking',
    destinationId: 'aru',
    season: 'Aug — Sep',
    description: '5-day expedition to the largest glacier in the Kashmir Valley (Kolahoi, 4,200 m) beneath Mt Kolahoi (5,425 m).',
    longDescription: 'For serious trekkers only. The Kolahoi Glacier is the largest in the Lidder watershed, sitting at 4,200 m beneath the 5,425 m Mt Kolahoi (also called "Kashmir\'s Matterhorn"). The 5-day expedition starts in Aru, follows the Lidder to Lidderwat, then climbs 1,200 m over two days to the glacier base camp. Includes a half-day glacier walk with crampons.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 38500,
    duration: '5 days',
    difficulty: 'Advanced',
    minAge: 16,
    maxGroup: 6,
    gear: '["Mountaineering boots","Crampons","Ice axe","Harness","Sleeping bag (-10°C)","Trekking poles"]',
    safety: '["UIAGM guide","Rope team","Glacier rescue kit","Satellite phone","First-aid + altitude meds"]',
  },
  {
    id: 'chadar-trek',
    name: 'Chadar Frozen River Trek',
    category: 'Trekking',
    destinationId: 'zanskar',
    season: 'Jan — Feb',
    description: '9-day winter trek on the frozen Zanskar River at temperatures of -25 °C. One of the world\'s most unique winter adventures.',
    longDescription: 'The Chadar ("sheet") Trek is a 9-day hike on the frozen Zanskar River through the Zanskar Gorge. Temperatures drop to -25 °C at night. Trekkers walk on the ice itself, sometimes on the banks when the ice is thin. Nights are spent in caves. A once-in-a-lifetime adventure — physically demanding but requiring no technical climbing skills.',
    image: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 48500,
    duration: '9 days',
    difficulty: 'Advanced',
    minAge: 18,
    maxGroup: 8,
    gear: '["Insulated boots (-30°C rated)","Multiple base layers","Down jacket","Sleeping bag (-20°C)","Insulated mat","Crampons (microspikes)","Thermos"]',
    safety: '["Local Zanskari guide","Ice condition assessment","Satellite phone","Helicopter rescue insurance","Full first-aid"]',
  },

  // ===== Water sports =====
  {
    id: 'lidder-river-rafting',
    name: 'Lidder River White-Water Rafting',
    category: 'Water',
    destinationId: 'pahalgam',
    season: 'Apr — Sep',
    description: 'Grade II–III rapids on the Lidder through pine forest — 8 km stretch from Mawoora to Pahalgam.',
    longDescription: 'The Lidder River offers excellent white-water from April to September when snowmelt swells the flow. The standard 8 km run from Mawoora village to Pahalgam has Grade II-III rapids — suitable for first-timers and families. Eliya uses IRF-certified guides, self-bailing rafts, and provides wetsuits for the early-season cold water.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 2800,
    duration: 'Half day',
    difficulty: 'Beginner',
    minAge: 12,
    maxGroup: 8,
    gear: '["Life jacket","Helmet","Paddle","Wetsuit (early season)","Dry bag"]',
    safety: '["IRF-certified guide","Safety kayak","Throw bags","First-aid","River rescue certified"]',
  },
  {
    id: 'sindh-river-rafting',
    name: 'Sindh River Rafting',
    category: 'Water',
    destinationId: 'sonamarg',
    season: 'May — Aug',
    description: 'Grade III–IV rapids on the Sindh for experienced rafters — 14 km from Sonmarg to Kangan.',
    longDescription: 'The Sindh River is more aggressive than the Lidder — Grade III-IV rapids through a steep gorge. The 14 km stretch from Sonmarg to Kangan is the standard run. Best in June-August when the flow is at its peak. Suitable for experienced rafters only; first-timers should do the Lidder first.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 4500,
    duration: 'Full day',
    difficulty: 'Intermediate',
    minAge: 16,
    maxGroup: 6,
    gear: '["Life jacket","Helmet","Paddle","Wetsuit","Dry bag"]',
    safety: '["IRF-certified guide","Safety kayak","Throw bags","River rescue certified","First-aid"]',
  },
  {
    id: 'dal-lake-kayaking',
    name: 'Dal Lake Kayaking & SUP',
    category: 'Water',
    destinationId: 'srinagar',
    season: 'Apr — Oct',
    description: 'Quiet paddle through the floating gardens and houseboat lanes of Dal Lake at dawn.',
    longDescription: 'The most peaceful way to see Dal Lake. Eliya offers dawn kayak and stand-up paddleboard (SUP) trips through the floating gardens, past the houseboat neighborhoods, and to the floating vegetable market at Meerakshah Chowk. Includes a kahwa break on a floating platform. 2-hour trips, suitable for ages 10+.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 1800,
    duration: '2 hours',
    difficulty: 'Beginner',
    minAge: 10,
    maxGroup: 6,
    gear: '["Kayak or SUP","Paddle","Life jacket","Dry bag","Sun hat"]',
    safety: '["Local guide","Life jacket","Shore support","First-aid"]',
  },
  {
    id: 'lidder-trout-fishing',
    name: 'Trout Fishing on the Lidder',
    category: 'Water',
    destinationId: 'pahalgam',
    season: 'Apr — Sep',
    description: 'Catch-and-release brown and rainbow trout on a 3 km private stretch of the Lidder with permits and gear included.',
    longDescription: 'The Lidder is one of India\'s finest trout streams — both brown and rainbow trout thrive in the cold glacial water. Eliya holds permits for a private 3 km stretch. We provide fly rods, waders, and a local ghillie (guide) who knows every pool. Catch-and-release only. Best in April-May and September.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 5500,
    duration: 'Half day',
    difficulty: 'Beginner to Intermediate',
    minAge: 12,
    maxGroup: 4,
    gear: '["Fly rod","Reel","Flies","Waders","Net","Permit"]',
    safety: '["Local ghillie","First-aid","River rescue","Weather monitoring"]',
  },

  // ===== Air sports =====
  {
    id: 'sanasar-paragliding',
    name: 'Paragliding at Sanasar',
    category: 'Air',
    destinationId: 'patnitop',
    season: 'May — Sep',
    description: 'Tandem paragliding off the Nathatop ridge near Patnitop — 15-20 minute flights with valley views.',
    longDescription: 'Sanasar, 19 km from Patnitop, is J&K\'s paragliding hub. Tandem flights take off from the Nathatop ridge (2,100 m) and land in the Sanasar meadow — 15-20 minute flights with views of the Pir Panjal and Shiwalik ranges. All pilots are FAI-certified. Best in May-September when thermals are reliable.',
    image: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 3500,
    duration: '15-20 min flight',
    difficulty: 'Beginner',
    minAge: 12,
    maxGroup: 1,
    gear: '["Harness (provided)","Helmet (provided)","Wind jacket","Closed shoes"]',
    safety: '["FAI-certified tandem pilot","Pre-flight weather check","Reserve parachute","Helmet"]',
  },
  {
    id: 'gulmarg-hot-air-balloon',
    name: 'Hot Air Balloon (Gulmarg)',
    category: 'Air',
    destinationId: 'gulmarg',
    season: 'May — Sep',
    description: 'Tethered hot-air balloon rides in the Gulmarg meadow — 30 minute flights with 360° Himalayan views.',
    longDescription: 'A tethered hot-air balloon operates in the Gulmarg meadow from May to September (weather permitting). Flights last 30 minutes and rise to 300 m above the meadow — panoramic views of Apharwat, the Pir Panjal range, and on clear days, Nanga Parbat (8,126 m) in Pakistan-administered Kashmir. Operated by J&K Tourism-licensed pilots.',
    image: 'https://images.unsplash.com/photo-1513415564515-763d91423bdd?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 6500,
    duration: '30 min flight',
    difficulty: 'Beginner',
    minAge: 8,
    maxGroup: 4,
    gear: '["Warm jacket","Closed shoes","Sunglasses","Camera"]',
    safety: '["Licensed pilot","Weather check","Tethered operation","Pre-flight safety briefing"]',
  },

  // ===== Climbing =====
  {
    id: 'drung-ice-climbing',
    name: 'Drung Waterfall Ice Climbing',
    category: 'Climbing',
    destinationId: 'tangmarg',
    season: 'Jan — Feb',
    description: 'Beginner ice climbing on the 60-m frozen Drung Waterfall near Tangmarg. All gear included.',
    longDescription: 'When the Drung Waterfall freezes solid in January, it becomes a 60-metre pillar of blue ice — perfect for learning ice climbing. Eliya\'s IFMGA guides run 1-day beginner courses covering proper ice axe technique, crampon use, and top-rope climbing. All technical gear provided (ice axes, crampons, harness, helmet, ropes).',
    image: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 8500,
    duration: 'Full day',
    difficulty: 'Beginner',
    minAge: 16,
    maxGroup: 4,
    gear: '["Ice axes (provided)","Crampons (provided)","Helmet (provided)","Harness (provided)","Warm layers","Insulated boots"]',
    safety: '["IFMGA guide","Top-rope setup","Ice condition assessment","First-aid","Pre-climb briefing"]',
  },
  {
    id: 'rock-climbing-sonamarg',
    name: 'Sport Rock Climbing (Sonmarg)',
    category: 'Climbing',
    destinationId: 'sonamarg',
    season: 'May — Sep',
    description: 'Bolted limestone routes from 5.6 to 5.11 on the cliffs above Sonmarg — half-day and full-day options.',
    longDescription: 'The limestone crags above Sonmarg have ~25 bolted sport routes from French 4 to 7a (5.6 to 5.11d YDS), developed by local climbers. Routes range from 15 to 35 metres. Eliya provides ropes, quickdraws, harnesses, climbing shoes, and a certified instructor. Suitable for first-timers (top-rope) and experienced climbers (lead).',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 4500,
    duration: 'Half or full day',
    difficulty: 'Beginner to Advanced',
    minAge: 12,
    maxGroup: 4,
    gear: '["Climbing shoes (provided)","Harness (provided)","Helmet (provided)","Rope & quickdraws (provided)","Chalk bag"]',
    safety: '["Certified instructor","Bolts checked annually","Top-rope setup for beginners","First-aid"]',
  },

  // ===== Mountain biking =====
  {
    id: 'gulmarg-mtb',
    name: 'Mountain Biking (Gulmarg)',
    category: 'Cycling',
    destinationId: 'gulmarg',
    season: 'May — Sep',
    description: 'Downhill MTB from Apharwat Peak (4,390 m) to Gulmarg — 1,700 m vertical drop on pony trails and dirt tracks.',
    longDescription: 'Take the gondola to Apharwat Peak with your bike, then descend 1,700 m back to Gulmarg on a mix of pony trails and 4x4 tracks. Guides adjust the route based on rider level — easier routes through the meadow for beginners, steeper tree runs for advanced. Full-suspension bikes and protective gear included.',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 6500,
    duration: 'Full day',
    difficulty: 'Intermediate to Advanced',
    minAge: 14,
    maxGroup: 6,
    gear: '["Full-suspension MTB (provided)","Full-face helmet (provided)","Knee pads","Elbow pads","Gloves","Hydration pack"]',
    safety: '["Local guide","Trail-side first-aid","Bike repair kit","Weather monitoring"]',
  },

  // ===== Camel & pony rides =====
  {
    id: 'hunder-camel',
    name: 'Bactrian Camel Ride (Hunder Dunes)',
    category: 'Other',
    destinationId: 'nubra',
    season: 'May — Sep',
    description: '30-minute ride on the silver sand dunes of Hunder on a double-humped Bactrian camel — a Silk Road legacy.',
    longDescription: 'The sand dunes at Hunder, in the Nubra Valley, are unique — a cold desert at 3,048 m altitude. The Bactrian (two-humped) camels that give rides here are descendants of the pack animals that travelled the Silk Road through the Karakoram. A 30-minute ride along the dunes costs ₹500 per person; Eliya arranges private sunset rides with photography.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    priceFrom: 1500,
    duration: '30 min ride',
    difficulty: 'Beginner',
    minAge: 5,
    maxGroup: 4,
    gear: '["Sun hat","Sunscreen","Sunglasses","Closed shoes"]',
    safety: '["Camel handler","Pre-ride briefing","First-aid"]',
  },
]

async function seedAdventures() {
  console.log('🌱 Seeding adventure sports...')
  for (const a of adventures) {
    await db.adventureSport.upsert({
      where: { id: a.id },
      update: a,
      create: a,
    })
  }
  console.log(`  ✓ ${adventures.length} adventure sports`)
  console.log('')
  console.log('Categories:')
  const cats = adventures.reduce<Record<string, number>>((acc, a) => {
    acc[a.category] = (acc[a.category] || 0) + 1
    return acc
  }, {})
  Object.entries(cats).forEach(([c, n]) => console.log(`  ${c}: ${n}`))
}

seedAdventures()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
