// ============================================================
// Eliya Tours — comprehensive Kashmir + Ladakh seed data
// Run: bun run /home/z/my-project/scripts/seed.ts
// ============================================================

import { db } from '../src/lib/db'

// ============================================================
// DESTINATIONS — covers all of Kashmir + Ladakh, grouped by area
// ============================================================
const destinations = [
  // ===== Kashmir Valley (Srinagar & around) =====
  {
    id: 'srinagar',
    name: 'Srinagar',
    region: 'Srinagar',
    area: 'Kashmir Valley',
    elevation: '1,585 m',
    bestSeason: 'Apr — Oct',
    tagline: 'The Venice of the East',
    description: 'Drift along Dal Lake on a hand-carved shikara, sleep on a cedar houseboat, and lose yourself in the symmetry of Mughal gardens laid out by emperors four centuries ago.',
    longDescription: 'Srinagar is the summer capital of Jammu & Kashmir and the gateway to every Eliya itinerary. The city wraps around Dal Lake and Nigeen Lake, with the Zabarwan Hills rising to the east. Our guests stay on traditional houseboats moored on Nigeen Lake — quieter than Dal, with the same Himalayan reflections. Mornings begin with a floating-vegetable-market shikara ride; afternoons are for the Mughal gardens of Shalimar, Nishat and Chashme Shahi; evenings end with kahwa on the prow of the boat as the sun sets behind the Pir Panjal range.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.62 0.13 165)',
    latitude: 34.0837,
    longitude: 74.7973,
    rating: 4.9, curated: 96, visitors: 78, safety: 92,
    highlights: '["Sunrise shikara on Dal Lake","Overnight cedar houseboat stay","Mughal gardens: Shalimar, Nishat, Chashme Shahi","Old Srinagar bazaar & Shah-e-Hamdan shrine"]',
  },
  {
    id: 'dal-lake',
    name: 'Dal Lake',
    region: 'Srinagar',
    area: 'Kashmir Valley',
    elevation: '1,583 m',
    bestSeason: 'Apr — Oct',
    tagline: 'The Jewel of Srinagar',
    description: 'Eight square kilometres of floating gardens, houseboat lanes and shikara channels. The floating vegetable market at dawn is one of Asia\'s only two.',
    longDescription: 'Dal Lake is the heart of Srinagar — fed by natural springs and the Telbal stream, drained by the Jhelum. The lake is famous for its houseboat neighborhoods (each with names like "Golden Lily" and "Prince of Wales"), the floating gardens that grow tomatoes and melons on woven reed rafts, and the dawn floating vegetable market at Meerakshah Chowk where shikaras gather to trade produce before first light.',
    image: 'https://images.unsplash.com/photo-1605649461784-1a8d20fbf3a8?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.55 0.13 200)',
    latitude: 34.1209, longitude: 74.8285,
    rating: 4.8, curated: 95, visitors: 72, safety: 90,
    highlights: '["Sunrise floating vegetable market","Shikara ride through floating gardens","Houseboat overnight on Nigeen arm","Evening char-chinar sunset point"]',
  },
  {
    id: 'pampore',
    name: 'Pampore',
    region: 'Srinagar',
    area: 'Kashmir Valley',
    elevation: '1,574 m',
    bestSeason: 'Oct — Nov (saffron bloom)',
    tagline: 'The Saffron Town',
    description: 'The only place in India where Crocus sativus grows. Three weeks of purple bloom in late October produce 90% of the country\'s saffron.',
    longDescription: 'Pampore, 14 km from Srinagar, is India\'s saffron capital. The purple crocus fields bloom for 3-4 weeks in late October through mid-November. Eliya arranges dawn harvest walks where guests pick their own saffron threads alongside Kashmiri women who have done this work for generations. The Pampore saffron is registered as GI-tagged "Kashmir Saffron" — the world\'s most expensive spice by weight, sold at ₹2-3 lakh per kilogram.',
    image: 'https://images.unsplash.com/photo-1499678329028-101435549a4e?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.72 0.17 65)',
    latitude: 33.9575, longitude: 74.9294,
    rating: 4.7, curated: 90, visitors: 30, safety: 93,
    highlights: '["Dawn saffron harvest walk","GI-tagged Kashmir saffron tasting","Kahwa-making workshop with local women","Saffrongrading & drying demo"]',
  },
  {
    id: 'sonamarg',
    name: 'Sonmarg',
    region: 'Ganderbal',
    area: 'Kashmir Valley',
    elevation: '2,800 m',
    bestSeason: 'May — Oct',
    tagline: 'The Meadow of Gold',
    description: 'The last town on the Srinagar–Ladakh road. From here the road climbs toward Zoji La — gateway to Ladakh — and the Thajiwas Glacier spills right down into the meadow.',
    longDescription: 'Sonmarg sits at 2,800 m, three hours northeast of Srinagar on the Sindh River. The meadow earns its name — "meadow of gold" — from the late-summer wildflowers that turn the slopes amber. Thajiwas Glacier is reachable on foot or by pony from town; for the more adventurous, the three-day trek to Vishansar, Krishansar and Gangabal Lakes begins at nearby Nichinai Pass. Sonmarg is also where Eliya stages the start of the trans-Himalayan journey to Ladakh.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.82 0.14 80)',
    latitude: 34.3001, longitude: 75.2905,
    rating: 4.8, curated: 87, visitors: 52, safety: 86,
    highlights: '["Pony trek to Thajiwas Glacier","Three-day alpine lakes trek (Vishansar–Krishansar)","Gateway to Zoji La & Ladakh","Sindh River white-water rafting"]',
  },
  {
    id: 'gurez',
    name: 'Gurez Valley',
    region: 'Bandipora',
    area: 'Kashmir Valley',
    elevation: '2,400 m',
    bestSeason: 'May — Sep',
    tagline: 'The Forgotten Valley',
    description: 'A 60-km valley beneath the Pir Panjal, cut off by snow for six months a year. The Dard-Shin people here speak Shina — not Kashmiri.',
    longDescription: 'Gurez is the most remote valley in Indian-administered Kashmir, reached by the Razdan Pass (3,300 m) which closes with the first snow. The valley follows the Kishanganga River along the Line of Control, with traditional wooden Dard-Shin villages — Dawar, Tulail, Chakwali — that look unchanged from a century ago. Eliya is one of only three operators permitted to bring guests here. Three-day trips include a homestay in Dawar, a day walk to the Habba Khatoon peak, and a trout-fishing afternoon on the Kishanganga.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.45 0.10 165)',
    latitude: 34.6500, longitude: 74.7500,
    rating: 4.9, curated: 98, visitors: 8, safety: 88,
    highlights: '["Dard-Shin village homestay","Habba Khatoon peak day hike","Kishanganga trout fishing","Razdan Pass drive (3,300 m)"]',
  },

  // ===== Pir Panjal Range (Gulmarg & around) =====
  {
    id: 'gulmarg',
    name: 'Gulmarg',
    region: 'Baramulla',
    area: 'Pir Panjal Range',
    elevation: '2,650 m',
    bestSeason: 'Dec — Mar (ski) / May — Sep (meadow)',
    tagline: 'The Meadow of Flowers',
    description: 'In winter, the highest gondola in the world drops you into chest-deep Himalayan powder. In summer, the same meadow bursts into a carpet of alpine wildflowers.',
    longDescription: 'Gulmarg sits at 2,650 m in the Pir Panjal range, a 90-minute drive from Srinagar. The Gulmarg Gondola — the second-highest cable car in the world — climbs to Apharwat Peak at 4,390 m, serving some of the longest, steepest and driest powder runs on the planet. Eliya partners with certified guides from the Indian Institute of Skiing and Mountaineering for every off-piste day. In summer the snow recedes to reveal a rolling meadow dotted with ponies, the 18-hole Gulmarg Golf Club (the highest green golf course in the world), and a network of day hikes to Khilanmarg and Alpather Lake.',
    image: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.72 0.17 65)',
    latitude: 34.0480, longitude: 74.3805,
    rating: 4.8, curated: 91, visitors: 65, safety: 88,
    highlights: '["Gondola to Apharwat Peak (4,390 m)","Off-piste powder skiing with certified guides","Summer wildflower meadows","Highest green golf course in the world"]',
  },
  {
    id: 'tangmarg',
    name: 'Tangmarg',
    region: 'Baramulla',
    area: 'Pir Panjal Range',
    elevation: '2,100 m',
    bestSeason: 'Mar — Oct',
    tagline: 'Gateway to Gulmarg',
    description: 'The last town before Gulmarg — pine forests, apple orchards and the Drung waterfall that freezes solid in January.',
    longDescription: 'Tangmarg is the base camp town for Gulmarg, 13 km below the meadow. It is where vehicles chain up for the winter climb and where Eliya bases its ski-support team. The Drung Waterfall, 8 km from town, freezes into a 60-metre ice pillar every January — Eliya runs ice-climbing days for beginners. Tangmarg is also the centre of the Kashmir apple belt; the September harvest fills the streets with crimson boxes of Delicious and Kashmiri American varieties.',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.42 0.08 145)',
    latitude: 34.0667, longitude: 74.4333,
    rating: 4.5, curated: 85, visitors: 25, safety: 90,
    highlights: '["Drung frozen waterfall ice-climb","Apple orchard harvest walks (Sep)","Pine-forest pony trails","Tangmarg handicraft market"]',
  },
  {
    id: 'lolab',
    name: 'Lolab Valley',
    region: 'Kupwara',
    area: 'Pir Panjal Range',
    elevation: '1,950 m',
    bestSeason: 'May — Oct',
    tagline: 'The Valley of Loves',
    description: 'A 25-km-long saucer valley in the north, with peach orchards, springs and the Kalaroos caves that locals believe lead to Russia.',
    longDescription: 'Lolab — "the valley of loves" — is a hidden saucer valley in Kupwara district, three hours north of Srinagar. The valley is famous for its natural springs (Lawnag, Khaimul, Bada Nag), its peach and walnut orchards, and the mysterious Kalaroos Caves carved into the limestone cliff above Satvana village. Local legend says the caves lead all the way to Russia; geologists say they extend at least 12 km. Eliya offers a 3-day Lolab exploration including a Kalaroos day hike, a night in a Kundla village homestay, and a dawn bird-watching walk.',
    image: 'https://images.unsplash.com/photo-1473773508845-188df298d2d1?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.38 0.09 150)',
    latitude: 34.4333, longitude: 74.2500,
    rating: 4.7, curated: 92, visitors: 12, safety: 87,
    highlights: '["Kalaroos Caves day hike","Lawnag Spring picnic","Kundla village homestay","Walnut & peach orchard walk"]',
  },

  // ===== Anantnag / Pahalgam region =====
  {
    id: 'pahalgam',
    name: 'Pahalgam',
    region: 'Anantnag',
    area: 'Lidder Valley',
    elevation: '2,240 m',
    bestSeason: 'Apr — Nov',
    tagline: 'The Valley of Shepherds',
    description: 'Pine forests, glacial rivers and the start of the Amarnath trail. Pahalgam is where Kashmir slows down — pony rides to Aru, white-water on the Lidder, evenings by a campfire.',
    longDescription: 'Pahalgam — "the village of shepherds" — sits at the confluence of the Lidder River and Sheshnag Lake streams, 95 km from Srinagar. It is the base for the annual Amarnath Yatra pilgrimage and for treks into the Great Himalayan Range. Eliya offers guided day hikes to Aru Valley, Betaab Valley and Chandanwari, plus overnight pack-pony expeditions to Kolahoi Glacier. The Lidder runs cold and clear through town — trout fishing permits and tackle are arranged by our local team.',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.42 0.08 145)',
    latitude: 34.0167, longitude: 75.3167,
    rating: 4.7, curated: 89, visitors: 58, safety: 90,
    highlights: '["Day hike to Aru & Betaab Valley","Trout fishing on the Lidder River","Kolahoi Glacier pony expedition","Campfire nights under Milky Way"]',
  },
  {
    id: 'aru',
    name: 'Aru Valley',
    region: 'Anantnag',
    area: 'Lidder Valley',
    elevation: '2,408 m',
    bestSeason: 'May — Oct',
    tagline: 'The Last Motorable Village',
    description: 'Eleven km beyond Pahalgam, Aru is where the road ends and the Great Himalayan Range begins. Base for the Kolahoi Glacier and Tarsar–Marsar treks.',
    longDescription: 'Aru is the last village reachable by vehicle in the Lidder Valley — beyond it lies the Great Himalayan Range. The village itself is a quiet grazing meadow with ponies, pine forest and the roar of the Lidder. From Aru, the trails fan out: a 2-day trek to Lidderwat, a 3-day trek to Kolahoi Glacier (the largest in the valley), and the famous 4-day Tarsar–Marsar–Sundersar twin-lakes circuit. Eliya runs a fixed eco-camp here from June to September.',
    image: 'https://images.unsplash.com/photo-1473773508845-188df298d2d1?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.32 0.06 165)',
    latitude: 33.9900, longitude: 75.4200,
    rating: 4.8, curated: 93, visitors: 22, safety: 88,
    highlights: '["4-day Tarsar–Marsar twin-lakes trek","Kolahoi Glacier expedition","Lidderwat meadow camp","Pony rides through pine forest"]',
  },
  {
    id: 'yusmarg',
    name: 'Yusmarg',
    region: 'Badgam',
    area: 'Pir Panjal Range',
    elevation: '2,396 m',
    bestSeason: 'May — Oct',
    tagline: 'The Hidden Meadow',
    description: 'The Kashmir that locals keep to themselves. A quiet alpine meadow ringed by pine forest, with day hikes to Doodh Ganga and the frozen lake of Nilnag.',
    longDescription: 'Yusmarg — "the meadow of Jesus" — is the off-the-radar counterpart to Gulmarg and Pahalgam. Just 47 km from Srinagar but with a fraction of the crowds, it remains a quiet grazing meadow surrounded by dense pine. Eliya brings guests here for the silence: a day walk along the Doodh Ganga ("river of milk") to a cascading waterfall, or a pony trek to the sapphire Nilnag Lake at 4,000 m. There are no hotels here — only a small Eliya-managed eco-camp with six canvas tents and a cedar-fire kitchen.',
    image: 'https://images.unsplash.com/photo-1473773508845-188df298d2d1?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.32 0.06 165)',
    latitude: 33.8333, longitude: 74.5833,
    rating: 4.9, curated: 95, visitors: 28, safety: 94,
    highlights: '["Private eco-camp (six tents only)","Doodh Ganga waterfall hike","Nilnag Lake pony trek","Stargazing with telescope on clear nights"]',
  },
  {
    id: 'dachigam',
    name: 'Dachigam National Park',
    region: 'Harwan',
    area: 'Zabarwan Range',
    elevation: '1,700 – 4,300 m',
    bestSeason: 'Mar — Nov',
    tagline: 'The Last Refuge of the Hangul',
    description: 'A 141 km² national park protecting the only viable population of the Kashmir stag — the hangul. Dawn walks with park rangers, leopard tracks, black bear and over 150 bird species.',
    longDescription: 'Dachigam National Park, just 22 km from Srinagar, is the most accessible wilderness experience on the Eliya roster. The park climbs from 1,700 m at the entrance to over 4,300 m in the alpine upper reaches, hosting the critically endangered hangul (Kashmir stag), Himalayan black bear, leopard, and over 150 bird species including the Himalayan monal. Eliya holds permits for guided dawn walks accompanied by park rangers — the only way to enter the core zone. The lower Dagwan Valley trail follows a trout stream through pine and cedar; the upper Tarsar trail requires a two-day trek with overnight camp.',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.55 0.15 145)',
    latitude: 34.1333, longitude: 75.0333,
    rating: 4.7, curated: 92, visitors: 22, safety: 91,
    highlights: '["Ranger-led dawn hangul safari","Himalayan monal & black bear sightings","Lower Dagwan Valley trout trail","Two-day Tarsar alpine lake trek"]',
  },
  {
    id: 'verinag',
    name: 'Verinag Spring',
    region: 'Anantnag',
    area: 'Pir Panjal Range',
    elevation: '1,876 m',
    bestSeason: 'Mar — Nov',
    tagline: 'The Source of the Jhelum',
    description: 'An octagonal Mughal pool built by Jahangir in 1620, fed by a deep spring that is the source of the Jhelum River — Kashmir\'s lifeline.',
    longDescription: 'Verinag is the southernmost Mughal garden in Kashmir, built by Jahangir around the spring that is the source of the Jhelum. The octagonal pool (built by Shah Jahan\'s governor Ali Mardan Khan in 1629) is 16 metres deep and never varies in volume, even in drought years. The spring feeds a channel that becomes the Jhelum River — flowing 200 km north through Srinagar and into Wular Lake. Eliya includes Verinag on every south-Kashmir circuit, paired with the nearby Achabal gardens and the Martand Sun Temple ruins.',
    image: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.50 0.10 200)',
    latitude: 33.5476, longitude: 75.2582,
    rating: 4.5, curated: 88, visitors: 18, safety: 92,
    highlights: '["Octagonal Mughal spring pool","Source of the Jhelum River","Pair with Martand Sun Temple","Trout farm at nearby Kokernag"]',
  },
  {
    id: 'martand',
    name: 'Martand Sun Temple',
    region: 'Anantnag',
    area: 'Pir Panjal Range',
    elevation: '1,950 m',
    bestSeason: 'Mar — Nov',
    tagline: 'The Kashmiri Parthenon',
    description: 'An 8th-century sun temple perched on a plateau above Anantnag — one of the most spectacular ruins in India, often called the "Kashmiri Parthenon".',
    longDescription: 'The Martand Sun Temple was built by King Lalitaditya Muktapida of the Karkota dynasty around 725 CE. The temple, dedicated to Surya (the sun god), stands on a plateau 8 km east of Anantnag with views over the entire Kashmir Valley. It was destroyed in the 15th century by Sikandar Shah Miri, but the surviving ruins — 84 columns, a central shrine, and a colonnaded courtyard — are still among the most impressive ancient structures in India. Eliya pairs Martand with Verinag Spring and Achabal Gardens on a day-tour from Srinagar.',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.62 0.13 35)',
    latitude: 33.7300, longitude: 75.2500,
    rating: 4.6, curated: 90, visitors: 15, safety: 93,
    highlights: '["8th-century Karkota dynasty ruins","84-column colonnaded courtyard","Valley-view sunset from plateau","Pair with Verinag & Achabal day tour"]',
  },

  // ===== Jammu region =====
  {
    id: 'vaishno-devi',
    name: 'Vaishno Devi',
    region: 'Katra',
    area: 'Jammu Region',
    elevation: '1,584 m (shrine)',
    bestSeason: 'Mar — Oct (year-round)',
    tagline: 'The Holy Cave Shrine',
    description: 'One of the most-visited Hindu pilgrimage sites in India — a 13-km uphill trek from Katra to a cave shrine of the Mother Goddess at 1,584 m.',
    longDescription: 'Vaishno Devi is a cave shrine dedicated to the Hindu Mother Goddess, located at an altitude of 1,584 m in the Trikuta Mountains above the town of Katra. The 13-km uphill trek from Katra to the cave passes through Banganga, Charan Paduka and Adhkuwari before reaching the sanctum. Eliya organizes the pilgrimage end-to-end: helicopter bookings (one-way from Katra to Sanjichhat), VIP darshan slips, accommodation at the shrine board\'s guest house, and the return trek or chopper ride. The shrine receives 10 million pilgrims a year — booking 60+ days in advance is essential.',
    image: 'https://images.unsplash.com/photo-1542640244-7e672d6cef4e?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.62 0.18 350)',
    latitude: 33.0310, longitude: 74.9490,
    rating: 4.9, curated: 95, visitors: 88, safety: 94,
    highlights: '["13-km uphill trek to the cave shrine","Helicopter from Katra to Sanjichhat","VIP darshan slip arrangement","Ardh Kuwari cave passage"]',
  },
  {
    id: 'patnitop',
    name: 'Patnitop',
    region: 'Udhampur',
    area: 'Jammu Region',
    elevation: '2,024 m',
    bestSeason: 'Mar — Oct (winter for snow)',
    tagline: 'The Meadow Plateau',
    description: 'A plateau meadow on the Jammu–Srinagar highway, surrounded by deodar forest. Winter brings snow-tubing and skiing; summer brings paragliding.',
    longDescription: 'Patnitop (originally "Patan da Talab" — "the pond of the princess") sits at 2,024 m on the Jammu–Srinagar National Highway, 110 km from Jammu. It is the most convenient Himalayan meadow stop for travelers driving from the plains. The plateau is ringed by dense deodar (Himalayan cedar) forest, with views of the Pir Panjal and Shiwalik ranges. Winter (Dec–Feb) brings 1-2 metres of snow and a small beginner ski slope; summer opens paragliding off the Nathatop ridge, pony rides to Sanasar, and forest walks to the Madhatop meadow.',
    image: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.45 0.10 145)',
    latitude: 33.0833, longitude: 75.2833,
    rating: 4.4, curated: 82, visitors: 45, safety: 92,
    highlights: '["Paragliding off Nathatop ridge","Beginner ski slope in winter","Deodar forest walk to Madhatop","Sanasar pony ride & lake"]',
  },

  // ===== Ladakh region =====
  {
    id: 'leh',
    name: 'Leh',
    region: 'Leh',
    area: 'Ladakh',
    elevation: '3,500 m',
    bestSeason: 'May — Sep',
    tagline: 'The Capital of Ladakh',
    description: 'The former Himalayan kingdom\'s capital — Buddhist monasteries, a 17th-century palace, and the gateway to every Ladakh itinerary.',
    longDescription: 'Leh is the capital of the Union Territory of Ladakh, sitting at 3,500 m in the Indus Valley. The town is dominated by the 9-storey Leh Palace (built 1553, modeled on the Potala in Lhasa) and surrounded by gompas (Buddhist monasteries) — Hemis, Thiksey, Shey, Stok, Spituk and Phyang. Eliya\'s standard Leh itinerary includes 2 days of acclimatization (essential at this altitude), day trips to the monasteries, and the old-town bazaar. Leh is the staging point for Nubra Valley, Pangong Lake and Tso Moriri.',
    image: 'https://images.unsplash.com/photo-1605649461784-1a8d20fbf3a8?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.72 0.13 60)',
    latitude: 34.1526, longitude: 77.5770,
    rating: 4.8, curated: 93, visitors: 70, safety: 86,
    highlights: '["9-storey Leh Palace (1553)","Hemis, Thiksey & Shey monasteries","Old-town bazaar & Shanti Stupa","Acclimatization day walks"]',
  },
  {
    id: 'nubra',
    name: 'Nubra Valley',
    region: 'Leh',
    area: 'Ladakh',
    elevation: '3,048 m',
    bestSeason: 'May — Sep',
    tagline: 'The Valley of Flowers (Ladakh)',
    description: 'A high-altitude cold desert beyond Khardung La (5,359 m) — sand dunes at Hunder, double-humped Bactrian camels, and Diskit monastery.',
    longDescription: 'Nubra Valley lies north of the Khardung La pass (at 5,359 m, one of the highest motorable roads in the world), reached by a 4-5 hour drive from Leh. The valley is technically a cold desert — the Shyok and Nubra rivers feed oasis villages of apricot orchards and barley fields. Hunder village has silver sand dunes where Bactrian camels (brought here by Silk Road caravans) give rides. Diskit Monastery, with its 32-metre Maitreya Buddha statue, overlooks the valley. Eliya runs 3-day Nubra trips including a night at a fixed camp in Hunder and a day at the Turtuk village (the last Indian village before the LoC, populated by Balti Muslims).',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.78 0.14 70)',
    latitude: 34.6868, longitude: 77.5619,
    rating: 4.9, curated: 95, visitors: 55, safety: 84,
    highlights: '["Cross Khardung La (5,359 m)","Hunder sand dunes & Bactrian camels","Diskit monastery 32-m Buddha","Turtuk village (last Indian village)"]',
  },
  {
    id: 'pangong',
    name: 'Pangong Lake',
    region: 'Leh',
    area: 'Ladakh',
    elevation: '4,225 m',
    bestSeason: 'May — Sep',
    tagline: 'The Lake That Changes Colour',
    description: 'A 134-km saltwater lake straddling India and Tibet, 60% of which lies in China. The water shifts from blue to green to grey across the day.',
    longDescription: 'Pangong Tso ("long, narrow, enchanted lake" in Tibetan) is a 134-km saltwater lake at 4,225 m altitude. Approximately 60% of its length lies in Chinese-administered Tibet. The lake is famous for changing colour — from deep sapphire at dawn, through turquoise at noon, to slate grey at dusk — and for the spot near Pangong camp where the Bollywood film "3 Idiots" was shot. Eliya runs 2-day trips from Leh via the Chang La pass (5,360 m) with an overnight at a fixed camp at Spangmik, returning via the same route. Photography permits and ITBP checkpoints are pre-arranged.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.55 0.14 220)',
    latitude: 33.7500, longitude: 78.6500,
    rating: 4.9, curated: 92, visitors: 60, safety: 82,
    highlights: '["Cross Chang La (5,360 m)","Spangmik camp overnight at 4,225 m","Lake colour shift photography","3 Idiots filming spot visit"]',
  },
  {
    id: 'kargil',
    name: 'Kargil',
    region: 'Kargil',
    area: 'Ladakh',
    elevation: '2,676 m',
    bestSeason: 'May — Sep',
    tagline: 'The Gateway to Zanskar',
    description: 'The second-largest town of Ladakh — base for the Drass War Memorial, the Suru Valley, and the Zanskar trekking region.',
    longDescription: 'Kargil sits on the Suru River at 2,676 m, 220 km from Srinagar via the Zoji La pass. It is the second town of Ladakh (after Leh) and the gateway to two remote regions: the Suru Valley south toward Zanskar, and the Drass region (the second-coldest inhabited place on Earth, with winter temperatures below −40 °C). Kargil is essential for travelers driving the Srinagar–Leh highway; Eliya pairs it with a visit to the Tololing Tiger Hill war memorial (1999 Kargil War), the Munshi Aziz Bhat museum of Central Asian trade, and a Suru Valley drive to the Kolahoi viewpoint at Parkachik.',
    image: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.60 0.12 50)',
    latitude: 34.5531, longitude: 76.1349,
    rating: 4.5, curated: 88, visitors: 35, safety: 86,
    highlights: '["Drass War Memorial & Tiger Hill","Suru Valley drive to Parkachik","Munshi Aziz Bhat trade museum","Gateway to Zanskar trekking"]',
  },
  {
    id: 'zanskar',
    name: 'Zanskar Valley',
    region: 'Kargil',
    area: 'Ladakh',
    elevation: '3,500 – 7,000 m',
    bestSeason: 'Jun — Sep',
    tagline: 'The Frozen River Kingdom',
    description: 'A 7,000-sq-km trans-Himalayan valley reachable by one road. Winter brings the Chadar — the frozen-river trek on the Zanskar.',
    longDescription: 'Zanskar is the most remote valley in Ladakh — a 7,000 sq km basin ringed by the Zanskar and Great Himalayan ranges, reachable by road only from June to October via the Pensi La pass (4,400 m). The capital Padum has just 1,500 people. The valley is the starting point for the famous Chadar Trek — a 9-day winter hike on the frozen Zanskar River at temperatures below −25 °C. In summer, Eliya runs the Padum–Phugtal–Karsha circuit with monastery stays and a 4-day trek to the Phugtal Monastery, built into a cliff above the Tsarap River.',
    image: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.50 0.10 220)',
    latitude: 33.4667, longitude: 76.5333,
    rating: 4.9, curated: 96, visitors: 10, safety: 78,
    highlights: '["9-day Chadar frozen-river trek (Jan–Feb)","Phugtal Monastery cliff-stay","Pensi La pass drive (4,400 m)","Karsha & Stongdey monastery visits"]',
  },
  {
    id: 'tso-moriri',
    name: 'Tso Moriri',
    region: 'Leh',
    area: 'Ladakh',
    elevation: '4,522 m',
    bestSeason: 'May — Sep',
    tagline: 'The Mountain Lake',
    description: 'A 26-km high-altitude lake in the Rupshu plateau — quieter than Pangong, surrounded by 6,000-m peaks, home to bar-headed geese and black-necked cranes.',
    longDescription: 'Tso Moriri is a 26-km-long brackish lake at 4,522 m in the Rupshu plateau of southeastern Ladakh. It is part of the Tso Moriri Wetland Conservation Reserve (a Ramsar site), hosting migratory birds including black-necked cranes, bar-headed geese, and Brahminy ducks. The lake is ringed by 6,000-m peaks — Lungser Kangri (6,666 m) rises directly above the eastern shore. Eliya runs 3-day trips from Leh via the Taglang La pass (5,328 m, the second-highest motorable road in the world), with overnights at a fixed camp at Korzok village and a visit to the 400-year-old Korzok Monastery.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1600&q=80',
    gallery: '[]',
    accent: 'oklch(0.50 0.14 200)',
    latitude: 32.9000, longitude: 78.3000,
    rating: 4.8, curated: 91, visitors: 18, safety: 80,
    highlights: '["Taglang La pass crossing (5,328 m)","Korzok Monastery (400 yrs)","Black-necked crane watching","Lungser Kangri 6,666 m backdrop"]',
  },
]

// ============================================================
// SEASONS — six seasonal packages
// ============================================================
const seasons = [
  {
    id: 'spring',
    season: 'Spring',
    months: 'Mar — Apr',
    title: 'Blossom & Tulip Season',
    theme: 'Mughal Gardens Awakening',
    description: 'The Indira Gandhi Memorial Tulip Garden opens in late March with 1.5 million blooms across 70 varieties — the largest tulip garden in Asia. The almond trees of Badamwari bloom pink against the snowmelt-fed streams, and Shalimar and Nishat gardens reopen their terraced water channels for the season.',
    longDescription: 'Spring is the gentlest season in Kashmir — temperatures hold at 15-22 °C, the snowline recedes above 3,500 m, and the valley turns pink and white with almond, cherry and peach blossom. The Indira Gandhi Memorial Tulip Garden opens in late March and runs through mid-April with 1.5 million tulips across 70 varieties — the largest tulip garden in Asia. Eliya\'s spring circuit pairs the gardens with the Badamwari almond walk, the Pampore saffron fields (off-season but worth the visit), a shikara ride on Dal Lake, and a 3-day extension to Pahalgam for early-season Betaab Valley views.',
    image: 'https://images.unsplash.com/photo-1513415564515-763d91423bdd?auto=format&fit=crop&w=1200&q=80',
    color: 'oklch(0.78 0.16 350)',
    priceFrom: 24500,
    duration: '5 nights',
    isFeatured: false,
    destinations: '["srinagar","dal-lake","pampore","pahalgam"]',
    itinerary: '[{"day":1,"title":"Arrive Srinagar","desc":"Airport pickup, houseboat check-in on Nigeen Lake, sunset shikara ride."},{"day":2,"title":"Mughal gardens & Tulip Garden","desc":"Nishat, Shalimar and Chashme Shahi, then the Tulip Garden at peak bloom."},{"day":3,"title":"Old Srinagar & Pampore","desc":"Shah-e-Hamdan shrine, Zaina Kadal bazaar, afternoon drive to Pampore saffron fields."},{"day":4,"title":"Drive to Pahalgam","desc":"3-hr drive via Awantipora ruins. Betaab Valley walk, Lidder riverside evening."},{"day":5,"title":"Aru Valley & return","desc":"Pony trek to Aru Valley, return to Srinagar for farewell Wazwan dinner."}]',
  },
  {
    id: 'summer',
    season: 'Summer',
    months: 'May — Jul',
    title: 'Alpine Meadows & Glacial Lakes',
    theme: 'High-Altitude Trekking',
    description: 'Snow recedes from the high passes and the great Kashmir treks open — the three-day Vishansar–Krishansar–Gangabal circuit, the Tarsar–Marsar twin-lakes trek, and day hikes to Thajiwas and Apharwat. Temperatures in the valley hold at a perfect 24°C.',
    longDescription: 'Summer is the peak trekking season in Kashmir — the high passes clear of snow by mid-June and the alpine meadows burst into wildflower bloom. Eliya runs three signature summer treks: the 4-day Tarsar–Marsar–Sundersar twin-lakes circuit out of Aru, the 3-day Vishansar–Krishansar–Gangabal lakes trek out of Sonmarg, and the 5-day Kolahoi Glacier expedition. For non-trekkers, summer is also ideal for the Srinagar–Leh highway (open June–October), with stops at Sonmarg, Drass, Kargil and the Pangong Lake. Day temperatures in the valley hold at a perfect 24 °C.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    color: 'oklch(0.55 0.15 165)',
    priceFrom: 38900,
    duration: '7 nights',
    isFeatured: true,
    destinations: '["sonamarg","pahalgam","aru","yusmarg"]',
    itinerary: '[{"day":1,"title":"Arrive Srinagar → Sonmarg","desc":"Drive to Sonmarg (3 hrs), acclimatize at meadow camp."},{"day":2,"title":"Nichinai Pass trek","desc":"Begin the Vishansar–Krishansar trek. 6-hr walk to Nichinai camp."},{"day":3,"title":"Vishansar & Krishansar lakes","desc":"Cross Nichinai Pass (4,100 m). Camp above Krishansar Lake."},{"day":4,"title":"Gangabal Lake descent","desc":"Cross Gadsar Pass (4,200 m) to Gangabal Lake. Return to Sonmarg."},{"day":5,"title":"Drive to Pahalgam","desc":"Via Srinagar. Afternoon Lidder riverside walk."},{"day":6,"title":"Aru & Betaab Valley","desc":"Pony trek to Aru, picnic at Betaab Valley."},{"day":7,"title":"Return to Srinagar","desc":"Houseboat farewell dinner on Nigeen Lake."}]',
  },
  {
    id: 'monsoon',
    season: 'Late Summer',
    months: 'Aug — Sep',
    title: 'Saffron Harvest in Pampore',
    theme: 'Cultural & Culinary',
    description: 'The purple crocus fields of Pampore bloom for only three weeks in late October — but the harvest rituals, kahwa-making workshops, and saffron-picking walks begin in August with the harvest preparation. Pair with the apple harvest of Shopian and the walnut groves of Anantnag.',
    longDescription: 'Late summer and early autumn in Kashmir is the harvest season — apples in Shopian, walnuts in Anantnag, and the world\'s most expensive spice (saffron) in Pampore. Eliya\'s saffron harvest trip runs from late October through mid-November (the bloom window), with pre-harvest preparation trips available from August. Guests stay in Pampore with a saffron-farming family, wake before dawn to pick the purple crocus flowers before the sun wilts them, and learn to separate and dry the three red stigmas that become commercial saffron. Pair with the apple harvest in Shopian (September), the walnut harvest in Anantnag (October), and the chinar-turning in Srinagar (November).',
    image: 'https://images.unsplash.com/photo-1499678329028-101435549a4e?auto=format&fit=crop&w=1200&q=80',
    color: 'oklch(0.72 0.17 65)',
    priceFrom: 29500,
    duration: '6 nights',
    isFeatured: false,
    destinations: '["pampore","srinagar","verinag","martand"]',
    itinerary: '[{"day":1,"title":"Arrive Srinagar","desc":"Houseboat on Nigeen. Evening kahwa ceremony."},{"day":2,"title":"Drive to Pampore","desc":"Stay with a saffron-farming family. Afternoon field walk and grading workshop."},{"day":3,"title":"Dawn saffron harvest","desc":"Pre-sunrise crocus picking. Stigma separation and drying demo."},{"day":4,"title":"Shopian apple orchards","desc":"Drive to Shopian. Apple harvest participation in a Delicious orchard."},{"day":5,"title":"Anantnag walnuts & Martand","desc":"Walnut grove walk, picnic at Martand Sun Temple ruins."},{"day":6,"title":"Verinag & return to Srinagar","desc":"Source of the Jhelum at Verinag Spring, return for farewell dinner."}]',
  },
  {
    id: 'autumn',
    season: 'Autumn',
    months: 'Oct — Nov',
    title: 'Chinar Gold & Mughal Gardens',
    theme: 'Photography & Heritage',
    description: 'The chinar trees — brought to Kashmir by the Mughals — turn the colour of burnished copper. Nishat and Shalimar gardens become a photographer\'s dream, with falling leaves drifting across the stone water channels. The harvest season brings fresh apples, walnuts and the year\'s saffron to market.',
    longDescription: 'Autumn (locally "Harud") is the photographer\'s season in Kashmir. The chinar trees (Platanus orientalis), brought to Kashmir by the Mughals in the 17th century, turn from green through gold to deep rust over six weeks. The Mughal gardens of Nishat, Shalimar, Chashme Shahi and Pari Mahal become living tapestries — falling chinar leaves drift across the terraced water channels, and the Zabarwan Hills behind turn the same colour. Eliya\'s autumn itinerary pairs garden photography with the harvest markets of old Srinagar (fresh apples, walnuts, saffron and quince), a Dachigam day trip for the hangul rutting season, and an optional Pahalgam extension for early snow on the peaks above.',
    image: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1200&q=80',
    color: 'oklch(0.62 0.18 40)',
    priceFrom: 32500,
    duration: '6 nights',
    isFeatured: false,
    destinations: '["srinagar","dal-lake","dachigam","pahalgam"]',
    itinerary: '[{"day":1,"title":"Arrive Srinagar","desc":"Houseboat on Nigeen. Sunset at Char Chinar."},{"day":2,"title":"Mughal gardens photography","desc":"Nishat, Shalimar, Chashme Shahi in peak chinar colour."},{"day":3,"title":"Pari Mahal & old Srinagar","desc":"Sunrise at Pari Mahal, old-city bazaar, saffron market."},{"day":4,"title":"Dachigam hangul rut","desc":"Dawn ranger walk to see the Kashmir stag in rutting season."},{"day":5,"title":"Drive to Pahalgam","desc":"Betaab Valley, Lidder riverside. First snow on Kolahoi peak."},{"day":6,"title":"Return to Srinagar","desc":"Farewell Wazwan dinner on the houseboat."}]',
  },
  {
    id: 'winter',
    season: 'Winter',
    months: 'Dec — Feb',
    title: 'Heli-Ski & Frozen Waterfalls',
    theme: 'Powder & Adventure',
    description: 'Gulmarg receives 14+ metres of snow annually. Eliya\'s heli-ski packages drop you onto untracked faces in the Pir Panjal, with day trips to the frozen waterfalls of Drung and the snow-shoe trails of Tangmarg. Evenings are spent around wood stoves in cedar cabins.',
    longDescription: 'Winter in Kashmir is for skiers and snow-lovers. Gulmarg receives an average of 14+ metres of snow annually — among the driest, lightest powder on Earth thanks to the cold continental climate. Eliya\'s winter packages offer three tiers: (1) resort skiing at Gulmarg with gondola access to Apharwat (4,390 m), (2) guided off-piste ski touring with certified guides, and (3) full heli-ski packages dropping onto untracked faces in the Pir Panjal. Non-skiers get the frozen Drung waterfall ice-climb, snow-shoe trails in Tangmarg, and houseboat stays on the partially-frozen Dal Lake with the rare "winter shikara" through floating ice.',
    image: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1200&q=80',
    color: 'oklch(0.85 0.03 240)',
    priceFrom: 64500,
    duration: '7 nights',
    isFeatured: true,
    destinations: '["gulmarg","tangmarg","srinagar","dal-lake"]',
    itinerary: '[{"day":1,"title":"Arrive Srinagar","desc":"Houseboat on Dal. Acclimatize, gear check."},{"day":2,"title":"Drive to Gulmarg","desc":"Gondola to Apharwat (4,390 m). First tracks."},{"day":3,"title":"Gulmarg off-piste","desc":"Certified guide-led bowl skiing. Aprés at the Khyber."},{"day":4,"title":"Heli-ski day","desc":"3 runs on untracked Pir Panjal faces. Return to Gulmarg."},{"day":5,"title":"Tangmarg & Drung","desc":"Snow-shoe walk in Tangmarg, afternoon ice-climb Drung waterfall."},{"day":6,"title":"Return to Srinagar","desc":"Winter shikara on Dal. Evening kahwa by wood stove."},{"day":7,"title":"Departure","desc":"Airport drop. Optional Sonmarg winter extension."}]',
  },
  {
    id: 'houseboat',
    season: 'Year-Round',
    months: 'Any month',
    title: 'Houseboat Heritage Stay',
    theme: 'Slow Living',
    description: 'A two-night stay on a hand-carved cedar houseboat on Nigeen Lake — the quieter, deeper sister of Dal. Includes a private shikara, kahwa ceremonies, a Wazwan dinner cooked on board, and a dawn visit to the floating vegetable market.',
    longDescription: 'The Kashmir houseboat is a unique institution — there are no permanent buildings on the lakes, so the British Raj engineered floating cedar palaces with carved walnut panels, Mughal-style drawing rooms and modern plumbing. Eliya\'s heritage houseboat package is the slowest, most meditative experience on the roster: two nights on a family-owned boat on Nigeen Lake (the quieter, deeper sister of Dal), with a private shikara for daily lake excursions, kahwa ceremonies on the prow at sunset, a traditional Wazwan dinner (36 dishes, cooked on board for 6+ hours) and a 5am shikara to the floating vegetable market. Available year-round, though winter (Dec-Feb) brings a frozen-edge lake and migrating birds.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    color: 'oklch(0.45 0.10 200)',
    priceFrom: 18900,
    duration: '2 nights',
    isFeatured: false,
    destinations: '["srinagar","dal-lake"]',
    itinerary: '[{"day":1,"title":"Board the houseboat","desc":"Airport pickup, midday shikara transfer to the boat. Afternoon at leisure. Sunset kahwa ceremony."},{"day":2,"title":"Floating market & Mughal gardens","desc":"5am shikara to floating vegetable market. Late breakfast. Nishat & Shalimar gardens by shikara."},{"day":3,"title":"Wazwan farewell","desc":"Wazwan dinner (36 dishes) cooked on board. Morning departure."}]',
  },
]

// ============================================================
// HOTELS — sample properties per destination
// ============================================================
const hotels = [
  { id: 'eliya-houseboat-nigeen', name: 'Eliya Heritage Houseboat', destinationId: 'srinagar', type: 'Houseboat', starRating: 4, description: 'A family-owned cedar houseboat with three bedrooms, carved walnut panels, and a private shikara. Moored on the quieter Nigeen Lake.', longDescription: 'Built in 1972 by the Bhat family and continuously run by them since. Three ensuite bedrooms, a Mughal-style drawing room, and a rooftop deck for kahwa ceremonies. Includes a private shikara for daily excursions.', image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80', gallery: '[]', priceFrom: 8500, amenities: '["Private shikara","Kahwa ceremony","Wazwan dinner on board","Walnut-wood carved interiors","Ensuite bathrooms","Wifi (limited)"]', rooms: 3 },
  { id: 'khyber-gulmarg', name: 'The Khyber Himalayan Resort', destinationId: 'gulmarg', type: 'Resort', starRating: 5, description: 'A 5-star luxury resort at the base of the Gulmarg gondola, with heated rooms, a spa, and panoramic Apharwat views.', longDescription: 'The Khyber is the only 5-star property in Gulmarg — 86 rooms and suites spread across cedar-clad chalets at 2,650 m. Heated marble floors, a 60-foot indoor pool, a Sofitel-standard spa, and direct gondola access. The restaurant serves Kashmiri Wazwan and continental cuisine.', image: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1200&q=80', gallery: '[]', priceFrom: 28500, amenities: '["Heated rooms","Indoor pool","Spa & sauna","Direct gondola access","Ski rental","Restaurant & bar","Wifi"]', rooms: 86 },
  { id: 'pine-grove-pahalgam', name: 'Pine Grove Eco Lodge', destinationId: 'pahalgam', type: 'Lodge', starRating: 3, description: 'A riverside eco-lodge on the Lidder with 12 cottages, fireplaces, and trout-fishing permits on site.', longDescription: 'Pine Grove is a family-run lodge with 12 cedar cottages along the Lidder River. Each cottage has a wood stove, a private deck, and mountain views. The lodge holds trout-fishing permits for a 3-km stretch of the Lidder and arranges pony treks to Aru and Betaab Valley.', image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80', gallery: '[]', priceFrom: 6500, amenities: '["Wood stove","Private deck","Trout-fishing permits","Pony trek arrangement","Restaurant","Campfire"]', rooms: 12 },
  { id: 'grand-leh', name: 'The Grand Dragon Leh', destinationId: 'leh', type: 'Hotel', starRating: 4, description: 'A modern hotel in central Leh with oxygen-enriched rooms, ideal for the first two nights of acclimatization.', longDescription: 'The Grand Dragon is the top-rated hotel in Leh — 59 rooms with oxygen enrichment (essential for the first 2 nights at 3,500 m), underfloor heating, and a rooftop restaurant with views of the Stok Kangri range. 5 minutes\' walk from the main bazaar and 10 from Leh Palace.', image: 'https://images.unsplash.com/photo-1605649461784-1a8d20fbf3a8?auto=format&fit=crop&w=1200&q=80', gallery: '[]', priceFrom: 12500, amenities: '["Oxygen-enriched rooms","Underfloor heating","Rooftop restaurant","Travel desk","Wifi","Airport shuttle"]', rooms: 59 },
  { id: 'nubra-camp', name: 'Hunder Sand Dunes Camp', destinationId: 'nubra', type: 'Camp', starRating: 3, description: 'A fixed-tent camp at the edge of the Hunder sand dunes, with attached bathrooms and Bactrian-camel rides on site.', longDescription: 'A fixed camp of 20 Swiss-tents with attached bathrooms, hot water, and electric blankets. The camp sits at the edge of the Hunder sand dunes — wake up to the sound of Bactrian camels outside your tent. Includes breakfast and dinner.', image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80', gallery: '[]', priceFrom: 5500, amenities: '["Swiss tents","Attached bathroom","Electric blanket","Camel ride arrangement","Bonfire","Meals included"]', rooms: 20 },
  { id: 'pangong-camp', name: 'Spangmik Lake Camp', destinationId: 'pangong', type: 'Camp', starRating: 2, description: 'Basic but comfortable lakeside camp at Spangmik, with views of Pangong from every tent.', longDescription: 'A simple lakeside camp of 15 tents at Spangmik village, 4 km from the ITBP checkpoint. Tents have cots, extra blankets, and shared squat toilets. Hot water by bucket. The view of Pangong at dawn — the lake shifts from black to sapphire to turquoise — is worth every discomfort.', image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80', gallery: '[]', priceFrom: 4500, amenities: '["Lake-facing tents","Cots & extra blankets","Bucket hot water","Meals included","Bonfire"]', rooms: 15 },
  { id: 'yusmarg-eco-camp', name: 'Eliya Yusmarg Eco-Camp', destinationId: 'yusmarg', type: 'Camp', starRating: 3, description: 'A six-tent private eco-camp in the Yusmarg meadow, run by Eliya. Cedar-fire kitchen, telescope for stargazing.', longDescription: 'Eliya\'s private eco-camp in Yusmarg — just six canvas tents with cots and extra blankets, a shared cedar-fire kitchen, and a Celestron telescope for the unpolluted night skies. The only accommodation in the Yusmarg meadow itself. Includes all meals and a guided Doodh Ganga waterfall hike.', image: 'https://images.unsplash.com/photo-1473773508845-188df298d2d1?auto=format&fit=crop&w=1200&q=80', gallery: '[]', priceFrom: 7500, amenities: '["Six private tents","Cedar-fire kitchen","Stargazing telescope","Guided hikes","All meals included","Campfire"]', rooms: 6 },
  { id: 'the-lalit-srinagar', name: 'The Lalit Grand Palace', destinationId: 'srinagar', type: 'Hotel', starRating: 5, description: 'A 5-star heritage hotel in a former Maharaja\'s palace, with 113 rooms and panoramic Dal Lake views.', longDescription: 'The Lalit Grand Palace Srinagar is a heritage property — originally built in 1910 as the palace of Maharaja Pratap Singh. 113 rooms and suites, set in 15 acres of Mughal-style gardens on the Gupkar Road overlooking Dal Lake. Indoor pool, spa, fine-dining restaurant, and a vintage car collection.', image: 'https://images.unsplash.com/photo-1513415564515-763d91423bdd?auto=format&fit=crop&w=1200&q=80', gallery: '[]', priceFrom: 22500, amenities: '["Heritage palace building","15-acre Mughal gardens","Indoor heated pool","Spa","Fine-dining restaurant","Vintage car collection","Wifi"]', rooms: 113 },
]

// ============================================================
// ADMIN USERS (PINs — demo plain text, in prod use bcrypt)
// ============================================================
const adminUsers = [
  { name: 'Tariq Bhat', email: 'tariq@eliyatours.in', pin: '901234', role: 'admin' },
  { name: 'Imran Bhat', email: 'imran@eliyatours.in', pin: '567890', role: 'editor' },
  { name: 'Sales Desk', email: 'sales@eliyatours.in', pin: '111111', role: 'sales' },
]

// ============================================================
// SEED FUNCTION
// ============================================================
async function seed() {
  console.log('🌱 Seeding destinations...')
  for (const d of destinations) {
    await db.destination.upsert({
      where: { id: d.id },
      update: d,
      create: d,
    })
  }
  console.log(`  ✓ ${destinations.length} destinations`)

  console.log('🌱 Seeding seasons...')
  for (const s of seasons) {
    await db.season.upsert({
      where: { id: s.id },
      update: s,
      create: s,
    })
  }
  console.log(`  ✓ ${seasons.length} seasons`)

  console.log('🌱 Seeding hotels...')
  for (const h of hotels) {
    await db.hotel.upsert({
      where: { id: h.id },
      update: h,
      create: h,
    })
  }
  console.log(`  ✓ ${hotels.length} hotels`)

  console.log('🌱 Seeding admin users...')
  for (const u of adminUsers) {
    await db.adminUser.upsert({
      where: { email: u.email },
      update: { name: u.name, pin: u.pin, role: u.role },
      create: { name: u.name, email: u.email, pin: u.pin, role: u.role },
    })
  }
  console.log(`  ✓ ${adminUsers.length} admin users`)
  console.log('')
  console.log('✅ Seed complete')
  console.log('')
  console.log('Admin credentials (PIN-based):')
  adminUsers.forEach(u => console.log(`  ${u.email} → PIN: ${u.pin} (${u.role})`))
}

seed()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
